FILTER 11KV BUT  INCLUDE ALL THE VALUE OF 11KV BECAUSE OF 11Kv, 11KV, 11kV

REMOVE DT AND USE 11KV VOATGE FILE

REMOVING LEADING 00 FROM THE FEEDERID AND SWITCH_IDS and retain also diconnected switches
and map all the link by source sfl and find all root note and then do bfs

rank logic new with connected component

NEW CODE EWMOVW DUPICATE ROWS AND HANDLE DTATA TYPE

In [ ]:
# ONE-CELL PIPELINE  ─────────────────────────────────────────────────────────
from __future__ import annotations
import sys, re
from collections import defaultdict, deque
from pathlib import Path
from typing import Dict, List, Tuple, Set

import pandas as pd

sys.setrecursionlimit(200_000)

# ───────────────────────── CONFIG ──────────────────────────────────────────
BASE = "/media/sagark24/New Volume/MERGE CDIS"

INPUT_HT      = f"{BASE}/2-Year-data/CLEANED_DATA/ht_cleaned.csv"
INPUT_EN      = f"{BASE}/2-Year-data/CLEANED_DATA/energyaudit_cleaned.csv"
OUTPUT        = f"{BASE}/IPYNB_FILE/DATA_GENERATION/11_KV_FEEDER_ALL DATA/11_WITHOUTDT_CONNECTED_RANKED.csv"
LOST_IDS_OUT  = f"{BASE}/IPYNB_FILE/DATA_GENERATION/lost_feeder_ids.csv"
LOST_DATA_OUT = f"{BASE}/IPYNB_FILE/DATA_GENERATION/lost_feeders_full_data.csv"

FEEDER_ID_COL  = "FEEDERID"
SRC_SWITCH_COL = "SOURCE_SWITCH_ID"
DST_SWITCH_COL = "DESTINATION_SWITCH_ID"
SRC_LOC_COL    = "SOURCE_SSFL"
DST_LOC_COL    = "DESTINATION_SSFL"
FUNC_LOC_COL   = "FUNC_LOC"
DATE_COL       = "SYSTEM_DATE"
LOAD_COL       = "MD_KVA"
edge_cols      = [SRC_SWITCH_COL, DST_SWITCH_COL, SRC_LOC_COL, DST_LOC_COL]

# ─────────────────────── helper: canonicalise ALL string cols ──────────────
def canon_all(df: pd.DataFrame) -> pd.DataFrame:
    obj_cols = df.select_dtypes("object").columns
    for c in obj_cols:
        df[c] = (df[c].astype(str)          # make sure dtype=object
                       .str.strip()          # remove leading/trailing spaces
                       .str.upper()        # <-- uncomment for case-insensitive
                )
    return df

# ─────────────────────── helper: 11 kV feeder token  ───────────────────────
def feeder_token(val) -> str | None:
    s = str(val).upper().split("_")
    return s[2].lstrip("0") if len(s) >= 3 and s[1] == "11KV" else None

# ─────────────────────── load HT cleaned  ──────────────────────────────────
print("1. load + clean HT")
ht = canon_all(pd.read_csv(INPUT_HT, low_memory=False)).drop_duplicates()
ht["FEEDER_ID"] = ht[FEEDER_ID_COL].apply(feeder_token)


# ── 2) TRACE A SINGLE FEEDER → rows list ──────────────────────────────────
def trace_feeder(fid: str) -> List[dict]:
    sub = ht[ht["FEEDER_ID"] == fid][edge_cols].drop_duplicates()
    if sub.empty:
        return []

    # build adjacency
    edges: List[Tuple[str, str, str, str]] = [tuple(r) for r in sub.itertuples(index=False, name=None)]
    adj: Dict[str, List[Tuple]] = defaultdict(list)
    rev_adj: Dict[str, List[str]] = defaultdict(list)
    for s_sw, d_sw, s_loc, d_loc in edges:
        adj[s_loc].append((s_sw, d_sw, s_loc, d_loc))
        rev_adj[d_loc].append(s_loc)

    # pick roots whose SOURCE_SWITCH == feeder-id
    roots_raw = [e for e in edges if e[0] == fid]
    roots     = list({e[1]: e for e in roots_raw}.values()) or [edges[0]]

    # prune to reachable DAG (skip cycles)
    pruned: Dict[str, List[Tuple]] = defaultdict(list)
    visited: Set[str] = set()
    for _, _, start_loc, _ in roots:
        stack = [start_loc]
        while stack:
            loc = stack.pop()
            if loc in visited:
                continue
            visited.add(loc)
            for edge in adj.get(loc, []):
                _, _, _, child = edge
                if child in visited:
                    continue
                pruned[loc].append(edge)
                stack.append(child)

    # compute depth for trunk-first ordering
    all_nodes = set(pruned) | {e[3] for edges in pruned.values() for e in edges}
    out_deg = {n: len(pruned.get(n, [])) for n in all_nodes}
    rev2: Dict[str, List[str]] = defaultdict(list)
    for parent, child_edges in pruned.items():
        for *_, child in child_edges:
            rev2[child].append(parent)

    depth: Dict[str, int] = {}
    q = deque([n for n, d in out_deg.items() if d == 0])
    for leaf in q:
        depth[leaf] = 1
    while q:
        node = q.popleft()
        for parent in rev2.get(node, []):
            nd = depth[node] + 1
            if depth.get(parent, 0) < nd:
                depth[parent] = nd
            out_deg[parent] -= 1
            if out_deg[parent] == 0:
                q.append(parent)

    rows: List[dict] = []
    side_cnt: Dict[str, int] = defaultdict(int)
    global_cnt = 0
    stack: List[Tuple[Tuple, str, bool]] = [(r, "", True) for r in reversed(roots)]

    while stack:
        edge, prefix, spine = stack.pop()
        src_sw, dst_sw, src_loc, dst_loc = edge

        if prefix == "":
            global_cnt += 1
            rank = str(global_cnt)
        elif spine:
            parts = prefix.split(".")
            rank = ".".join([*parts[:-1], str(int(parts[-1]) + 1)]) if parts[:-1] else str(int(parts[-1]) + 1)
        else:
            side_cnt[prefix] += 1
            rank = f"{prefix}.{side_cnt[prefix]}"

        rows.append(
            dict(
                FEEDER_ID=fid,
                FROM_TO=f"{src_sw}-{dst_sw}",
                SOURCE_LOCATION=src_loc,
                DESTINATION_LOCATION=dst_loc,
                RANK=rank,
                FROM_SWITCH=src_sw,
                TO_SWITCH=dst_sw,
            )
        )

        kids = sorted(pruned.get(dst_loc, []), key=lambda e: depth.get(e[3], 1), reverse=True)
        for s in reversed(kids[1:]):  # side branches first
            stack.append((s, rank, False))
        if kids:
            stack.append((kids[0], rank, True))

    return rows
# ─────────────────────── trace every feeder  ───────────────────────────────
print("2. trace feeders")
traces=[]
for i,fid in enumerate(ht["FEEDER_ID"].dropna().unique(),1):
    if i==1 or i%100==0: print(f"   {i}. FEEDER {fid}")
    traces.extend(trace_feeder(fid))
trace_df=pd.DataFrame(traces)
trace_df= trace_df.drop_duplicates()
# ─────────────────────── load + prep audit  ────────────────────────────────
print("3. merge energy audit")
audit = canon_all(pd.read_csv(INPUT_EN, low_memory=False, parse_dates=[DATE_COL]))
audit = audit.drop_duplicates([FUNC_LOC_COL, DATE_COL, LOAD_COL])
audit.columns=[c.upper() for c in audit.columns]

agg=(audit[[FUNC_LOC_COL,DATE_COL,LOAD_COL]]
        .dropna(subset=[FUNC_LOC_COL])
        .groupby(FUNC_LOC_COL)
        .agg(LATEST_DT_DATE=(DATE_COL,"max"),DT_LOAD=(LOAD_COL,"mean"))
        .reset_index())

merged=(trace_df.merge(agg,how="left",
                       left_on="DESTINATION_LOCATION",
                       right_on=FUNC_LOC_COL)
                 .drop(columns=[FUNC_LOC_COL]))
merged["LATEST_DT_DATE"]=pd.to_datetime(merged["LATEST_DT_DATE"]).dt.date
merged["LOCATION"]=merged["DESTINATION_LOCATION"]

# ─────────────────────── filter malformed FROM_TO  ────────────────────────
is_pair=lambda x: bool(re.fullmatch(r"\d+-\d+",str(x)))
kept   = merged[merged["FROM_TO"].apply(is_pair)]
dropped= merged[~merged["FROM_TO"].apply(is_pair)]

lost=sorted(set(merged["FEEDER_ID"]) - set(kept["FEEDER_ID"]))
pd.Series(lost,name="LOST_FEEDER_ID").to_csv(LOST_IDS_OUT,index=False)
dropped.to_csv(LOST_DATA_OUT,index=False)


# ─────────────────────── export  ───────────────────────────────────────────
OUT_COLS=["FEEDER_ID","FROM_TO","SOURCE_LOCATION","DESTINATION_LOCATION",
          "LOCATION","RANK","LATEST_DT_DATE","DT_LOAD"]
kept = kept.sort_values(by=["FEEDER_ID", "RANK"], na_position="last")
kept.to_csv(OUTPUT,index=False,columns=OUT_COLS)
print(f" saved {len(kept):,} rows → {OUTPUT}")

# preview
from IPython.display import display
display(kept.head(5))

1. load + clean HT
2. trace feeders
   1. FEEDER 15454
   100. FEEDER 41897
   200. FEEDER 28223
   300. FEEDER 39624
   400. FEEDER 41709
   500. FEEDER 31267
   600. FEEDER 28674
   700. FEEDER 35873
   800. FEEDER 30135
   900. FEEDER 18093
   1000. FEEDER 30031
   1100. FEEDER 3101
   1200. FEEDER 35038
   1300. FEEDER 30886
   1400. FEEDER 19090
3. merge energy audit
 saved 8,481 rows → /media/sagark24/New Volume/MERGE CDIS/IPYNB_FILE/DATA_GENERATION/11_KV_FEEDER_ALL DATA/11_WITHOUTDT_CONNECTED_RANKED.csv

,FEEDER_ID,FROM_TO,SOURCE_LOCATION,DESTINATION_LOCATION,RANK,FROM_SWITCH,TO_SWITCH,LATEST_DT_DATE,DT_LOAD,LOCATION
119,10205,10205-18556,1S-MH-MU-ZSC-RSTN-AMBI,1S-MH-MU-ZSC-CL09-2382,1,10205,18556,2025-04-04,616.320000,1S-MH-MU-ZSC-CL09-2382
120,10205,18558-18559,1S-MH-MU-ZSC-CL09-2382,1S-MH-MU-ZSC-CL09-2383,2,18558,18559,2025-04-04,674.080488,1S-MH-MU-ZSC-CL09-2383
121,10205,10205-10634,1S-MH-MU-ZSC-RSTN-AMBI,1S-MH-MU-ZSC-CL09-2723,2,10205,10634,2025-03-06,473.442574,1S-MH-MU-ZSC-CL09-2723
130,10205,16951-4853,1S-MH-MU-ZSC-CL09-2723,1S-MH-MU-ZSC-CL09-2366,2.1,16951,4853,2025-03-06,148.855367,1S-MH-MU-ZSC-CL09-2366
131,10205,4855-6089,1S-MH-MU-ZSC-CL09-2366,1S-MH-MU-ZSC-CL09-2348,2.2,4855,6089,2025-03-06,400.698507,1S-MH-MU-ZSC-CL09-2348

In [2]:
df= pd.read_csv(OUTPUT)
col = df['FEEDER_ID'].unique()
print("Unique FEEDER_ID values:", len(col))

Unique FEEDER_ID values: 1099

In [3]:
# After your 'kept' DataFrame is ready...

# 1. Identify feeders with only main chain (no sub-branches)
def is_main_chain_only(subdf):
    return all('.' not in r for r in subdf['RANK'])

# 2. Group by FEEDER_ID, check for main chain only
main_chain_flags = (
    kept.groupby('FEEDER_ID')
        .apply(is_main_chain_only)
        .rename('IS_MAIN_CHAIN_ONLY')
        .reset_index()
)

# 3. Calculate statistics
n_total = main_chain_flags.shape[0]
n_main  = main_chain_flags['IS_MAIN_CHAIN_ONLY'].sum()
percent_main = 100 * n_main / n_total if n_total else 0

print(f"Feeders with only main chain (no sub-chains): {n_main} of {n_total} ({percent_main:.2f}%)")

Feeders with only main chain (no sub-chains): 467 of 1099 (42.49%)

/tmp/ipykernel_49718/2588241840.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(is_main_chain_only)

## Cell 1: Trace Feeder Network Topology

In [2]:
# ONE-CELL PIPELINE  ─────────────────────────────────────────────────────────
from __future__ import annotations
import sys, re
from collections import defaultdict, deque
from pathlib import Path
from typing import Dict, List, Tuple, Set

import pandas as pd

sys.setrecursionlimit(200_000)

# ───────────────────────── CONFIG ──────────────────────────────────────────
BASE = "/media/sagark24/New Volume/MERGE CDIS"

INPUT_HT      = f"{BASE}/2-Year-data/CLEANED_DATA/ht_cleaned.csv"
INPUT_EN      = f"{BASE}/2-Year-data/CLEANED_DATA/energyaudit_cleaned.csv"
OUTPUT        = f"{BASE}/IPYNB_FILE/DATA_GENERATION/11_KV_FEEDER_ALL DATA/11_WITHOUTDT_CONNECTED_RANKED.csv"
LOST_IDS_OUT  = f"{BASE}/IPYNB_FILE/DATA_GENERATION/lost_feeder_ids.csv"
LOST_DATA_OUT = f"{BASE}/IPYNB_FILE/DATA_GENERATION/lost_feeders_full_data.csv"

FEEDER_ID_COL  = "FEEDERID"
SRC_SWITCH_COL = "SOURCE_SWITCH_ID"
DST_SWITCH_COL = "DESTINATION_SWITCH_ID"
SRC_LOC_COL    = "SOURCE_SSFL"
DST_LOC_COL    = "DESTINATION_SSFL"
FUNC_LOC_COL   = "FUNC_LOC"
DATE_COL       = "SYSTEM_DATE"
LOAD_COL       = "MD_KVA"
edge_cols      = [SRC_SWITCH_COL, DST_SWITCH_COL, SRC_LOC_COL, DST_LOC_COL]

# ─────────────────────── helper: canonicalise ALL string cols ──────────────
def canon_all(df: pd.DataFrame) -> pd.DataFrame:
    obj_cols = df.select_dtypes("object").columns
    for c in obj_cols:
        df[c] = (df[c].astype(str)          # make sure dtype=object
                       .str.strip()          # remove leading/trailing spaces
                       .str.upper()        # <-- uncomment for case-insensitive
                )
    return df

# ─────────────────────── helper: 11 kV feeder token  ───────────────────────
def feeder_token(val) -> str | None:
    s = str(val).upper().split("_")
    return s[2].lstrip("0") if len(s) >= 3 and s[1] == "11KV" else None

# ─────────────────────── load HT cleaned  ──────────────────────────────────
print("1. load + clean HT")
ht = canon_all(pd.read_csv(INPUT_HT, low_memory=False)).drop_duplicates()
ht["FEEDER_ID"] = ht[FEEDER_ID_COL].apply(feeder_token)

# ── 2) TRACE A SINGLE FEEDER → rows list ──────────────────────────────────
def trace_feeder(fid: str) -> List[dict]:
    sub = ht[ht["FEEDER_ID"] == fid][edge_cols].drop_duplicates()
    if sub.empty:
        return []

    # build adjacency
    edges: List[Tuple[str, str, str, str]] = [tuple(r) for r in sub.itertuples(index=False, name=None)]
    adj: Dict[str, List[Tuple]] = defaultdict(list)
    rev_adj: Dict[str, List[str]] = defaultdict(list)
    for s_sw, d_sw, s_loc, d_loc in edges:
        adj[s_loc].append((s_sw, d_sw, s_loc, d_loc))
        rev_adj[d_loc].append(s_loc)

    # pick roots whose SOURCE_SWITCH == feeder-id
    roots_raw = [e for e in edges if e[0] == fid]
    roots     = list({e[1]: e for e in roots_raw}.values()) or [edges[0]]

    # prune to reachable DAG (skip cycles)
    pruned: Dict[str, List[Tuple]] = defaultdict(list)
    visited: Set[str] = set()
    for _, _, start_loc, _ in roots:
        stack = [start_loc]
        while stack:
            loc = stack.pop()
            if loc in visited:
                continue
            visited.add(loc)
            for edge in adj.get(loc, []):
                _, _, _, child = edge
                if child in visited:
                    continue
                pruned[loc].append(edge)
                stack.append(child)

    # compute depth for trunk-first ordering
    all_nodes = set(pruned) | {e[3] for edges in pruned.values() for e in edges}
    out_deg = {n: len(pruned.get(n, [])) for n in all_nodes}
    rev2: Dict[str, List[str]] = defaultdict(list)
    for parent, child_edges in pruned.items():
        for *_, child in child_edges:
            rev2[child].append(parent)

    depth: Dict[str, int] = {}
    q = deque([n for n, d in out_deg.items() if d == 0])
    for leaf in q:
        depth[leaf] = 1
    while q:
        node = q.popleft()
        for parent in rev2.get(node, []):
            nd = depth[node] + 1
            if depth.get(parent, 0) < nd:
                depth[parent] = nd
            out_deg[parent] -= 1
            if out_deg[parent] == 0:
                q.append(parent)

    rows: List[dict] = []
    side_cnt: Dict[str, int] = defaultdict(int)
    global_cnt = 0
    stack: List[Tuple[Tuple, str, bool]] = [(r, "", True) for r in reversed(roots)]

    while stack:
        edge, prefix, spine = stack.pop()
        src_sw, dst_sw, src_loc, dst_loc = edge

        if prefix == "":
            global_cnt += 1
            rank = str(global_cnt)
        elif spine:
            parts = prefix.split(".")
            rank = ".".join([*parts[:-1], str(int(parts[-1]) + 1)]) if parts[:-1] else str(int(parts[-1]) + 1)
        else:
            side_cnt[prefix] += 1
            rank = f"{prefix}.{side_cnt[prefix]}"

        rows.append(
            dict(
                FEEDER_ID=fid,
                FROM_TO=f"{src_sw}-{dst_sw}",
                SOURCE_LOCATION=src_loc,
                DESTINATION_LOCATION=dst_loc,
                RANK=rank,
                FROM_SWITCH=src_sw,
                TO_SWITCH=dst_sw,
            )
        )

        kids = sorted(pruned.get(dst_loc, []), key=lambda e: depth.get(e[3], 1), reverse=True)
        for s in reversed(kids[1:]):  # side branches first
            stack.append((s, rank, False))
        if kids:
            stack.append((kids[0], rank, True))

    return rows

# ─────────────────────── trace every feeder  ───────────────────────────────
print("2. trace feeders")
traces=[]
for i,fid in enumerate(ht["FEEDER_ID"].dropna().unique(),1):
    if i==1 or i%100==0: print(f"   {i}. FEEDER {fid}")
    traces.extend(trace_feeder(fid))
trace_df=pd.DataFrame(traces)
trace_df= trace_df.drop_duplicates()
print("Total traced rows:", len(trace_df))  
trace_df.head()
trace_df.to_csv("debug_trace_df.csv", index=False)

1. load + clean HT
2. trace feeders
   1. FEEDER 15454
   100. FEEDER 41897
   200. FEEDER 28223
   300. FEEDER 39624
   400. FEEDER 41709
   500. FEEDER 31267
   600. FEEDER 28674
   700. FEEDER 35873
   800. FEEDER 30135
   900. FEEDER 18093
   1000. FEEDER 30031
   1100. FEEDER 3101
   1200. FEEDER 35038
   1300. FEEDER 30886
   1400. FEEDER 19090
Total traced rows: 9263

## Cell 2: Merge with Energy Audit Data and Export

In [3]:
# # ─────────────────────── load + prep audit  ────────────────────────────────
# print("3. merge energy audit")
# audit = canon_all(pd.read_csv(INPUT_EN, low_memory=False, parse_dates=[DATE_COL]))
# audit = audit.drop_duplicates([FUNC_LOC_COL, DATE_COL, LOAD_COL])
# audit.columns=[c.upper() for c in audit.columns]

# agg=(audit[[FUNC_LOC_COL,DATE_COL,LOAD_COL]]
#         .dropna(subset=[FUNC_LOC_COL])
#         .groupby(FUNC_LOC_COL)
#         .agg(LATEST_DT_DATE=(DATE_COL,"max"),DT_LOAD=(LOAD_COL,"mean"))
#         .reset_index())

# merged=(trace_df.merge(agg,how="left",
#                        left_on="DESTINATION_LOCATION",
#                        right_on=FUNC_LOC_COL)
#                  .drop(columns=[FUNC_LOC_COL]))
# merged["LATEST_DT_DATE"]=pd.to_datetime(merged["LATEST_DT_DATE"]).dt.date
# merged["LOCATION"]=merged["DESTINATION_LOCATION"]
merged = (trace_df.copy())
col = merged['FEEDER_ID'].unique()
print("Unique FEEDER_ID values before merge:", len(col))
merged["LOCATION"]=merged["DESTINATION_LOCATION"]
# ─────────────────────── filter malformed FROM_TO  ────────────────────────
is_pair=lambda x: bool(re.fullmatch(r"\d+-\d+",str(x)))
kept   = merged[merged["FROM_TO"].apply(is_pair)]
dropped= merged[~merged["FROM_TO"].apply(is_pair)]

lost=sorted(set(merged["FEEDER_ID"]) - set(kept["FEEDER_ID"]))
print("Lost FEEDER_IDs:", len(lost))
pd.Series(lost,name="LOST_FEEDER_ID").to_csv(LOST_IDS_OUT,index=False)
dropped.to_csv(LOST_DATA_OUT,index=False)


# ─────────────────────── export  ───────────────────────────────────────────
OUT_COLS=["FEEDER_ID","FROM_TO","SOURCE_LOCATION","DESTINATION_LOCATION",
          "LOCATION","RANK","FROM_SWITCH","TO_SWITCH"]
kept = kept.sort_values(by=["FEEDER_ID", "RANK"], na_position="last")
kept.to_csv(OUTPUT,index=False,columns=OUT_COLS)
print(f" saved {len(kept):,} rows → {OUTPUT}")

# preview
from IPython.display import display
display(kept.head(5))
col = kept['FEEDER_ID'].unique()
print("Unique FEEDER_ID values:", len(col))

Unique FEEDER_ID values before merge: 1424
Lost FEEDER_IDs: 306
 saved 8,481 rows → /media/sagark24/New Volume/MERGE CDIS/IPYNB_FILE/DATA_GENERATION/11_KV_FEEDER_ALL DATA/11_WITHOUTDT_CONNECTED_RANKED.csv

,FEEDER_ID,FROM_TO,SOURCE_LOCATION,DESTINATION_LOCATION,RANK,FROM_SWITCH,TO_SWITCH,LOCATION
119,10205,10205-18556,1S-MH-MU-ZSC-RSTN-AMBI,1S-MH-MU-ZSC-CL09-2382,1,10205,18556,1S-MH-MU-ZSC-CL09-2382
120,10205,18558-18559,1S-MH-MU-ZSC-CL09-2382,1S-MH-MU-ZSC-CL09-2383,2,18558,18559,1S-MH-MU-ZSC-CL09-2383
121,10205,10205-10634,1S-MH-MU-ZSC-RSTN-AMBI,1S-MH-MU-ZSC-CL09-2723,2,10205,10634,1S-MH-MU-ZSC-CL09-2723
130,10205,16951-4853,1S-MH-MU-ZSC-CL09-2723,1S-MH-MU-ZSC-CL09-2366,2.1,16951,4853,1S-MH-MU-ZSC-CL09-2366
131,10205,4855-6089,1S-MH-MU-ZSC-CL09-2366,1S-MH-MU-ZSC-CL09-2348,2.2,4855,6089,1S-MH-MU-ZSC-CL09-2348

Unique FEEDER_ID values: 1118

## Seperate file for the energy load

In [4]:
# %%  ───────────────  Monthly DT_LOAD averages → merge & save  ─────────────
from pathlib import Path
import pandas as pd
import numpy as np

# ───── user-configurable year range ────────────────────────────────────────
START_YEAR = 2023          # inclusive
END_YEAR   = 2024          # inclusive

# ───── paths (identical to your earlier cells) ─────────────────────────────
BASE      = "/media/sagark24/New Volume/MERGE CDIS"
INPUT_EN  = f"{BASE}/2-Year-data/CLEANED_DATA/energyaudit_cleaned.csv"
OUTPUT= f"{BASE}/IPYNB_FILE/DATA_GENERATION/11_KV_FEEDER_ALL DATA/ENERGY_AUDIT_MONTHLY_AVG_LOAD.csv"
# ───── load Energy-Audit (only needed cols) ───────────────────────────────
audit = pd.read_csv(
    INPUT_EN,
    usecols=["FUNC_LOC", "SYSTEM_DATE", "MD_KVA"],
    parse_dates=["SYSTEM_DATE"],
    low_memory=False
)
audit.columns = audit.columns.str.upper()

# ───── restrict to desired year range ──────────────────────────────────────
mask_year = audit["SYSTEM_DATE"].dt.year.between(START_YEAR, END_YEAR)
audit_sub = audit.loc[mask_year].copy()

# ───── add Y, M keys & compute average load per (LOC, Y, M) ───────────────
audit_sub["YEAR"]  = audit_sub["SYSTEM_DATE"].dt.year
audit_sub["MONTH"] = audit_sub["SYSTEM_DATE"].dt.month

gb = (audit_sub
      .groupby(["FUNC_LOC", "YEAR", "MONTH"], sort=False)["MD_KVA"]
      .mean()
      .rename("AVG_MD_KVA")
      .reset_index())

# ───── ensure every location has all 12 months / year rows ────────────────
all_locs   = gb["FUNC_LOC"].unique()
all_idx    = pd.MultiIndex.from_product(
                 [all_locs,
                  range(START_YEAR, END_YEAR+1),
                  range(1,13)],
                 names=["FUNC_LOC", "YEAR", "MONTH"]
             )

gb_full = (gb.set_index(["FUNC_LOC","YEAR","MONTH"])
              .reindex(all_idx)
              .sort_index())

# ───── fill missing months by avg(prev,next) (linear interp) ───────────────
# forward/back fill edge gaps after interpolation
# ───── fill missing months by avg(prev,next) (linear interp) ──────────────
gb_full["AVG_MD_KVA"] = (
    gb_full.groupby(level=0)["AVG_MD_KVA"]          # level-0 = FUNC_LOC
           .transform(lambda s: (
               s.interpolate(method="linear", limit_direction="both")
                .ffill().bfill()                   # edge gaps
           ))
)

gb_full = gb_full.reset_index()

# ───── pivot to wide columns (e.g. DT_LOAD_2024_01) ───────────────────────
gb_full["COL_NAME"] = gb_full.apply(
    lambda r: f"DT_LOAD_{int(r.YEAR)}_{int(r.MONTH):02d}", axis=1
)
wide = (gb_full
        .pivot(index="FUNC_LOC", columns="COL_NAME", values="AVG_MD_KVA")
        .reset_index()
        .rename(columns={"FUNC_LOC":"LOCATION"}))

# ───── merge with existing ranked-file and save back ──────────────────────
wide.to_csv(OUTPUT, index=False)
print(f"Monthly averages merged ")

Monthly averages merged

## merge into the same file 11 kv network file

In [10]:
# %%  ─────────  ENERGY-AUDIT → monthly & daily DT_LOAD, merge in-place  ─────────
from pathlib import Path
import calendar, numpy as np, pandas as pd

# ── PARAMETERS ────────────────────────────────────────────────────────────────
START_YEAR = 2024          # inclusive
END_YEAR   = 2024          # inclusive

BASE      = "/media/sagark24/New Volume/MERGE CDIS"
INPUT_EN  = f"{BASE}/2-Year-data/CLEANED_DATA/energyaudit_cleaned.csv"
TOPO_CSV  = f"{BASE}/IPYNB_FILE/DATA_GENERATION/11_KV_FEEDER_ALL DATA/11_WITHOUTDT_CONNECTED_RANKED.csv"

# ── 1) ENERGY-AUDIT  → monthly average per (FUNC_LOC, YEAR, MONTH) ───────────
audit = (pd.read_csv(INPUT_EN,
                     usecols=["FUNC_LOC", "SYSTEM_DATE", "MD_KVA"],
                     parse_dates=["SYSTEM_DATE"],
                     low_memory=False)
           .rename(columns=str.upper))

audit = audit[audit["SYSTEM_DATE"].dt.year.between(START_YEAR, END_YEAR)].copy()
audit["YEAR"]  = audit["SYSTEM_DATE"].dt.year
audit["MONTH"] = audit["SYSTEM_DATE"].dt.month

gb = (audit.groupby(["FUNC_LOC","YEAR","MONTH"], sort=False)["MD_KVA"]
            .mean().rename("AVG_MD_KVA").reset_index())

# ensure every (loc, year, month) exists → interpolate & edge-fill
full_idx = pd.MultiIndex.from_product(
              [gb["FUNC_LOC"].unique(),
               range(START_YEAR, END_YEAR+1),
               range(1, 13)],
              names=["FUNC_LOC","YEAR","MONTH"])
gb = (gb.set_index(["FUNC_LOC","YEAR","MONTH"])
        .reindex(full_idx).sort_index())

gb["AVG_MD_KVA"] = (gb.groupby(level=0)["AVG_MD_KVA"]
                      .transform(lambda s: (s.interpolate("linear",
                                                          limit_direction="both")
                                             .ffill().bfill())))
gb = gb.reset_index()

# ── 2) wide table with DT_LOAD_YYYY_MM columns ───────────────────────────────
gb["COL"] = gb.apply(lambda r: f"DT_LOAD_{r.YEAR}_{r.MONTH:02d}", axis=1)
monthly = (gb.pivot(index="FUNC_LOC", columns="COL", values="AVG_MD_KVA")
             .reset_index()
             .rename(columns={"FUNC_LOC": "LOCATION"}))

# ── 3) build DAY_<year>_<###> columns in one shot (no fragmentation) ─────────
day_frames = []
for yr in range(START_YEAR, END_YEAR+1):
    # month column repeated once per day in that month
    month_cols = [f"DT_LOAD_{yr}_{mo:02d}"
                  for mo in range(1, 13)
                  for _ in range(calendar.monthrange(yr, mo)[1])]
    if calendar.isleap(yr) and len(month_cols) == 365:      # add 366 for leap
        month_cols.append(f"DT_LOAD_{yr}_12")

    day_names = [f"DAY_{yr}_{i+1:03d}" for i in range(len(month_cols))]
    df_year   = monthly[month_cols].copy()
    df_year.columns = day_names
    day_frames.append(df_year)

# concatenate once → single memory block, no warnings
day_block = pd.concat(day_frames, axis=1)
monthly   = pd.concat([monthly, day_block], axis=1)

# ── 4) merge into existing topology & overwrite the CSV ──────────────────────
topo   = pd.read_csv(TOPO_CSV, low_memory=False)
merged = topo.merge(monthly, on="LOCATION", how="left")
merged.to_csv(TOPO_CSV, index=False)

print(f" merged monthly & daily DT_LOAD into l{len(merged)}{TOPO_CSV}")

 merged monthly & daily DT_LOAD into l8481/media/sagark24/New Volume/MERGE CDIS/IPYNB_FILE/DATA_GENERATION/11_KV_FEEDER_ALL DATA/11_WITHOUTDT_CONNECTED_RANKED.csv

In [9]:
cl = merged['TO_SWITCH'].unique()
print("Unique FEEDER_ID values after merge:", len(cl))

Unique FEEDER_ID values after merge: 8222